Refact/add interactive map mapsandvisu
OCA-UFCG/oca-frontend pull request #109
Opened 2024-10-10 20:28 UTC by LazaroQueiroz

## Description

This PR add interactivity in the map of Maps & Visu's Section.

## How to test it

You'll only need to run it and access the `/` route and see if it works properly. The map should initialize at "Cisternas" map and keep changing the layer over the time.
The map should not allow moving or zooming in this section.

2024-10-14 18:08 UTC, abraaovalentim requested changes
Before adding interactivity, we had a small border around the static image of the map, I think it would be a good idea to keep this border for visual reasons
![Captura de tela de 2024-10-14 15-05-03](https://github.com/user-attachments/assets/29db955f-54f8-49c7-91d1-7c70afe33e1f)
Other than that, I think everything is fine

2024-10-14 18:08 UTC, abraaovalentim commented on src/components/MapsSection/MapsSection.styles.tsx
> +  height: 650px;
I believe that the height of 550px is better for reasons of standardization with the other sections, in addition to keeping the layout smaller, more reduced. By covering the entire page, we have a very strong focus on previewing
```suggestion
  height: 550px;
```

2024-10-14 18:09 UTC, LazaroQueiroz commented on src/components/MapsSection/MapsSection.styles.tsx
> +  height: 650px;
sure! i'll fix that. thanks.

2024-10-16 19:45 UTC, abraaovalentim approved these changes

2024-10-16 19:51 UTC, merged