Fix/sources loading
OCA-UFCG/oca-frontend pull request #143
Opened 2024-11-12 11:54 UTC by cilasmarques

This PR make 2 things:
1 - Fix the source loading. It, waits the source loading to append the layer, avoiding load errors
2 - Load all the sources asynchronously.

To test, access the map page.

2024-11-12 15:29 UTC, RodrigoEC requested changes
Really good!

Just commented some things on code but there's some other that I saw on the code and I think we'll could improve. I'm gonna list them here:

## Map initialization

![image](https://github.com/user-attachments/assets/84e8cce4-13d6-48cd-a411-d17b9c3e6daa)

Could be just like this:

```js
useEffect(() => {
    initializeMap();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);
```

## Unused if statement
The if statement on AddPopupEffect is never called beacuase the id + year will never be an unkown key

![image](https://github.com/user-attachments/assets/97eda52d-4861-4588-b9a9-80f9a4c346f8)

2024-11-12 15:29 UTC, RodrigoEC commented on src/components/MapTiff/MapTiff.tsx
> +      const yearStr = year ? year : "general";
```suggestion
      const yearStr = year || "general";
```

2024-11-12 15:29 UTC, RodrigoEC commented on src/components/MapTiff/MapTiff.tsx
> +      if (map && !map.getLayer(sourceKey)) {
```suggestion
    if (loadedSources.has(sourceKey) && map && !map.getLayer(sourceKey)) {
```

2024-11-13 14:57 UTC, RodrigoEC requested changes

2024-11-13 14:57 UTC, RodrigoEC commented on src/components/MapTiff/MapTiff.tsx
> +        if (!isReduced)
With the new change you actually removed the property of not adding the popup effect on the  MapTiff's reduced version, I think just adding it again could solve the issue

2024-11-14 14:54 UTC, RodrigoEC approved these changes
## Great fix!

![abbot](https://github.com/user-attachments/assets/6b33ba46-a716-40b9-8b13-60868738062b)

2024-11-14 15:08 UTC, LazaroQueiroz approved these changes
LGTM!

2024-11-14 15:09 UTC, abraaovalentim approved these changes
LGTM!

2024-11-14 15:10 UTC, merged