Feat: CI/CD AWS
OCA-UFCG/oca-frontend pull request #145
Opened 2024-11-13 12:49 UTC by LazaroQueiroz

This PR adds a new CI/CD to the 2 AWS EC2 instances.
It automates the build and deploy in those instances, more specifically the deploy for production. 

# How to test it
This feat can be tested when a new tag is added to the repository, then it triggers GitHub Action which creates jobs and the automation starts.

## Changes
The changes were made in: .github/workflows/deploy-oca-yml

2024-11-13 15:57 UTC, cilasmarques requested changes

2024-11-13 15:57 UTC, cilasmarques commented on .github/workflows/deploy-oca.yml
>          run: sudo docker run --name ${{ vars.CONTAINER_NAME_PROD }} -p ${{ vars.HOST_PORT_PROD }}:${{ vars.CONTAINER_PORT }} -d ${{ vars.DOCKER_IMAGE_PROD }}:latest
```suggestion
      - name: Run new container
        run: sudo docker run --restart unless-stopped --name ${{ vars.CONTAINER_NAME_PROD }} -p ${{ vars.HOST_PORT_PROD }}:${{ vars.CONTAINER_PORT }} -d ${{ vars.DOCKER_IMAGE_PROD }}:latest
```

2024-11-13 15:57 UTC, cilasmarques commented on .github/workflows/deploy-oca.yml
> +    runs-on: x1-aws-self-hosted-runner
```suggestion
  primary-build:
    runs-on: primary-self-hosted-runner
```

2024-11-13 15:57 UTC, cilasmarques commented on .github/workflows/deploy-oca.yml
> +    runs-on: x2-aws-self-hosted-runner
```suggestion
  secondary-build:
    runs-on: secondary-self-hosted-runner
```

2024-11-13 15:57 UTC, cilasmarques commented on .github/workflows/deploy-oca.yml
> +        run: sudo docker run --name ${{ vars.CONTAINER_NAME_PROD }} -p ${{ vars.HOST_PORT_PROD }}:${{ vars.CONTAINER_PORT }} -d ${{ vars.DOCKER_IMAGE_PROD }}:latest
```suggestion
        run: sudo docker run --restart unless-stopped --name ${{ vars.CONTAINER_NAME_PROD }} -p ${{ vars.HOST_PORT_PROD }}:${{ vars.CONTAINER_PORT }} -d ${{ vars.DOCKER_IMAGE_PROD }}:latest
```

2024-11-13 15:57 UTC, cilasmarques commented on .github/workflows/deploy-oca.yml
> +      - name: Add network
```suggestion
      - name: Connect to oca network
```

2024-11-13 15:57 UTC, cilasmarques commented on .github/workflows/deploy-oca.yml
> +      - name: Add network
```suggestion
      - name: Connect to oca-network
```

2024-11-14 15:07 UTC, cilasmarques approved these changes

2024-11-14 15:14 UTC, RodrigoEC approved these changes

2024-11-14 15:15 UTC, abraaovalentim approved these changes
show of balls!

2024-11-14 17:17 UTC, merged