Creates a new tiling system for brazil states
OCA-UFCG/oca-frontend pull request #147
Opened 2024-11-22 18:52 UTC by abraaovalentim

This pull request introduces a new approach for serving data related to state boundaries and borders of Brazil. It replaces the use of an external GeoJSON file with an access route that returns vectors of specific points.

## How to Test
- Access the main route or the map routes.
- Compare the results with the production environment to ensure consistency and correctness.

2024-11-26 18:47 UTC, RodrigoEC requested changes

2024-11-26 18:47 UTC, RodrigoEC commented on src/app/api/tiles/[z]/[x]/[y]/route.ts
> +function tmsToGoogleY(y: number, zoom: number) {
We can improve this to something more meaningful

2024-11-26 18:47 UTC, RodrigoEC commented on src/app/api/tiles/[z]/[x]/[y]/route.ts
> +function tmsToGoogleY(y: number, zoom: number) {
maybe something that says what tms is, or adding a documentation to the function would be better

2024-12-02 16:51 UTC, cilasmarques approved these changes

2025-03-10 14:30 UTC, RodrigoEC approved these changes

2025-03-10 19:14 UTC, merged