Add a News Carousel
OCA-UFCG/oca-frontend pull request #69
Opened 2024-08-01 13:25 UTC by abraaovalentim

This PR introduces the creation of the NewsCarousel component and its integration into the new CarouselSection. The NewsCarousel dynamically displays news items with an auto-advancing feature and interactive navigation buttons. 

How to Test:
Add News in CMS
Check if the section appears on the main page with only one News
Add more News
Veirfy the news transition

2024-08-06 11:48 UTC, RodrigoEC requested changes
Great Work! Creating a carousel is rather boring, but you shined. Just added some refactoring suggestions.

![image](https://github.com/user-attachments/assets/24385571-7b5a-42a1-8547-d8d3d66b767e)

Rebeca would be proud

2024-08-06 11:48 UTC, RodrigoEC commented on src/app/page.tsx
>        <AboutSection />
```suggestion
```

2024-08-06 11:48 UTC, RodrigoEC commented on src/components/CarouselSection/CarouselSection.tsx
> +      setNewsItems([
I think it's best if we added this "default" value as the initial value of the newItems state, with it we won't need the "else" statement

2024-08-06 11:48 UTC, RodrigoEC commented on src/components/CarouselSection/NewsCarousel/NewsCarousel.styles.tsx
> +  background: none;
```suggestion
```

2024-08-06 11:48 UTC, RodrigoEC commented on src/components/CarouselSection/NewsCarousel/NewsCarousel.tsx
> +  const handleNext = (event?: { stopPropagation: () => void } | undefined) => {
We could refactor this function to be like a handle update, that receives either the operation string, like "next", or the function itself

2024-08-06 11:48 UTC, RodrigoEC commented on src/components/CarouselSection/NewsCarousel/NewsCarousel.tsx
> +  const funcDebounce = () => {
```suggestion
  const updateDebound = () => {
```

2024-08-06 11:48 UTC, RodrigoEC commented on src/components/CarouselSection/NewsCarousel/NewsCarousel.tsx
> +  const redirectUrl = () => {
Instead of using a function to redirect, it's best if we use a link (<a>) tag

2024-08-06 12:46 UTC, RodrigoEC approved these changes

2024-08-06 15:13 UTC, cilasmarques commented
I found a bug in smartphone screens.
![image](https://github.com/user-attachments/assets/f913b268-6d35-43fa-9677-1b5fbcbaf7f8)

2024-08-06 18:22 UTC, abraaovalentim commented
> I found a bug in smartphone screens. ![image](https://private-user-images.githubusercontent.com/38442139/355504143-f913b268-6d35-43fa-9677-1b5fbcbaf7f8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI5Njg3MTAsIm5iZiI6MTcyMjk2ODQxMCwicGF0aCI6Ii8zODQ0MjEzOS8zNTU1MDQxNDMtZjkxM2IyNjgtNmQzNS00M2ZhLTk2NzctMWI1ZmJjYmFmN2Y4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA2VDE4MjAxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdmOWU5Y2NlN2Y0MGJhYTBhMmIzODBhM2FiODI0ZWNlOTI4ODgyOWZmM2JkODNmMzNhZDZlMTQ0YTk0YWE4ZjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.CSwxsPjsdgRoh-rT8mM84qWRIm4Ed_JT2OORCjmcOi4)

well here I don't have this error
![Captura de tela de 2024-08-06 15-21-33](https://github.com/user-attachments/assets/29100261-75f3-435c-abfb-e0846c7ed793)

2024-08-07 12:05 UTC, cilasmarques commented
> > I found a bug in smartphone screens. ![image](https://private-user-images.githubusercontent.com/38442139/355504143-f913b268-6d35-43fa-9677-1b5fbcbaf7f8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI5Njg3MTAsIm5iZiI6MTcyMjk2ODQxMCwicGF0aCI6Ii8zODQ0MjEzOS8zNTU1MDQxNDMtZjkxM2IyNjgtNmQzNS00M2ZhLTk2NzctMWI1ZmJjYmFmN2Y4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA2VDE4MjAxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdmOWU5Y2NlN2Y0MGJhYTBhMmIzODBhM2FiODI0ZWNlOTI4ODgyOWZmM2JkODNmMzNhZDZlMTQ0YTk0YWE4ZjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.CSwxsPjsdgRoh-rT8mM84qWRIm4Ed_JT2OORCjmcOi4)
> 
> well here I don't have this error ![Captura de tela de 2024-08-06 15-21-33](https://private-user-images.githubusercontent.com/98324254/355559805-29100261-75f3-435c-abfb-e0846c7ed793.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMwMzIxNzcsIm5iZiI6MTcyMzAzMTg3NywicGF0aCI6Ii85ODMyNDI1NC8zNTU1NTk4MDUtMjkxMDAyNjEtNzVmMy00MzVjLWFiZmItZTA4NDZjN2VkNzkzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA3VDExNTc1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA1MWYwMDIwNDllYmJjYzYyN2EwNmMyZDdiNjBiOTljN2M2ODc1YTAyYzExZjY4ZjFhMmVlNjViZTgyMTA4ZjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.i35a8l6ODjMrqnpvOx6_Xb29yrPCc4z52x13mTLTa_c)

I checked here and it's because of the browser

2024-08-07 12:19 UTC, cilasmarques commented on src/components/CarouselSection/NewsCarousel/NewsCarousel.tsx
> +                : ""
```suggestion
            src={newsItems[index]?.fields.thumb.fields.file.url && `https://${newsItems[index]?.fields.thumb.fields.file.url}`}
```

2024-08-07 12:22 UTC, cilasmarques approved these changes

2024-08-07 13:56 UTC, merged