Add the New Team Page
OCA-UFCG/oca-frontend pull request #75
Opened 2024-08-09 14:05 UTC by abraaovalentim

2024-08-09 14:26 UTC, RodrigoEC requested changes
Well done, just commented a size change. The other thing I think would be better is to remove the box shadow from the lattes icon

2024-08-09 14:26 UTC, RodrigoEC commented on src/components/TeamMember/TeamMember.tsx
> +      <ExpandIcon id="expand" size={28} />
```suggestion
      <ExpandIcon id="expand" size={24} />
```

2024-08-12 13:30 UTC, cilasmarques approved these changes
LGTM :)

2024-08-12 16:48 UTC, RodrigoEC approved these changes

2024-08-12 17:38 UTC, merged