Contact Us
OCA-UFCG/oca-frontend pull request #77
Opened 2024-08-15 17:09 UTC by abraaovalentim

This pull request adds the "Fale Conosco" contact page.

### How to Use ###

Fill in the form with your name, email and message you would like to be responded to. An email from a generic account with the required fields will be sent to the oca email so that it can be responded to as quickly as possible.

2024-08-15 18:18 UTC, cilasmarques requested changes
![image](https://github.com/user-attachments/assets/e68d7333-d39c-4ada-8b84-7cd8f16f241d)

Nice job :)

Just an opinion: I think we could display a success message when the email is sent

2024-08-15 18:18 UTC, cilasmarques commented on src/app/api/mail/route.ts
> +    const to = process.env.NEXT_PUBLIC_MAIL_APP_TO;
Add these environment variables to the [.env.sample](https://github.com/OCA-UFCG/oca-frontend/blob/main/.env.sample) file.
Make sure to include a description of where to obtain the variables and an example of them.

2024-08-15 18:18 UTC, cilasmarques commented on src/app/contact-us/page.tsx
> +    setIsFormValid(isValid);
I guess it's important make a name.trim() and message.trim() here

2024-08-20 18:32 UTC, RodrigoEC approved these changes

2024-08-21 17:16 UTC, cilasmarques approved these changes

2024-08-21 17:18 UTC, merged