Refact/redesigning nossa historia pictures
OCA-UFCG/oca-frontend pull request #93
Opened 2024-10-08 18:44 UTC by LazaroQueiroz

This PR modifies the design of the pictures shown in "Nossa História" page. Before, one static image was displayed. Now, a slider of pictures is shown.

2024-10-10 17:02 UTC, RodrigoEC requested changes
There's one thing that I think is important o refactor, that's the size of the swiper on smaller screens.

We want this swiper to have these same proportions on every screen size:
![image](https://github.com/user-attachments/assets/1ed783b5-76c1-479d-91b9-7a63a84ef3b1)
   

This is what's actually happening on smaller sizes:

![image](https://github.com/user-attachments/assets/2c46eba5-2df3-45f1-8d80-359fe39ef8d9)

2024-10-10 17:02 UTC, RodrigoEC commented on src/app/about/page.tsx
> +  if (!content[0]) return <></>;
### Why should we not change to this implementation

It's not pretty good to have this here. The previous structure provides us a feature that's very important, the SSR (Server Side Rendering) where the HTML is built on the server side before being served to the client.

With this implementation we won't be able to access the content previously (on the server side) the content will be retrieve once the page is served, which is kinda bad 'cause we make the client spend network and it has a waiting time for the content to appear (it might not appear on localhost, but on production it may happen more frequently).

### I think I understand why you made this change

The react keeps saying that you can't render the Swiper on server side, it has to be on the client side, right? The reason for that is that the `Swiper` component uses hooks and states (JS basically) to be dynamic. A solution for that is to move the `Swiper` to a component file of its own and than import it to the page file. Doing that we can use the use client inside the Swiper file and not on the `page.tsx` file.

A good example is the `MapsSection` component on the main `app/page.tsx` file

2024-10-10 19:57 UTC, LazaroQueiroz commented on src/app/about/page.tsx
> +  if (!content[0]) return <></>;
Sure, I fixed this. Thanks for the tip. I'll keep that in mind from now on.

2024-10-10 19:58 UTC, LazaroQueiroz commented
Fixed the problems (almost sure about that)
!

2024-10-14 17:22 UTC, RodrigoEC requested changes
Commented very little changes. Great work 🚀

2024-10-14 17:22 UTC, RodrigoEC commented on src/components/Swiper/swiper-styles.css
> +    object-fit: cover;
```suggestion
    height: auto;
    object-fit: cover;
    aspect-ratio: 16 / 9;
```

2024-10-14 17:22 UTC, RodrigoEC commented on src/components/Swiper/swiper-styles.css
> +    width: 75%;
```suggestion
    width: 100%;
    max-width: 1000px;
```

2024-10-14 17:41 UTC, LazaroQueiroz commented on src/components/Swiper/swiper-styles.css
> +    object-fit: cover;
nice! thanks!

2024-10-14 17:41 UTC, LazaroQueiroz commented on src/components/Swiper/swiper-styles.css
> +    width: 75%;
nice! thanks!

2024-10-14 18:34 UTC, RodrigoEC approved these changes

2024-10-14 18:52 UTC, abraaovalentim requested changes
I think it would be interesting if the image on the carousel changed after a specific time, maybe 7 seconds

2024-10-14 20:06 UTC, abraaovalentim approved these changes

2024-10-14 20:07 UTC, merged